### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-leireriel#1]
Really cool job @leireriel!!!

Here you have some tips to improve the exercise:

//HTML
- [x] We need a nav tag
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, or background-color
- [x] Main section should fit 100% of the browser's height
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by leireriel** [comment]
done!

**Comment by oneeyedman** [comment]
Super well done, @leireriel!!

Good job!
